# Configuration for ai_network_security_ids
paths:
  train_csv: data/samples/train.csv
  test_csv: data/samples/test.csv
  model_path: models/ids_model.pkl
model:
  type: rf  # rf or dnn
  random_state: 42
  n_estimators: 200
  max_depth: null
  dnn_hidden: 64
  dnn_layers: 2
  dnn_lr: 0.001
  dnn_epochs: 10
  dnn_batch_size: 64
train:
  test_size: 0.2
  stratify: true
  shuffle: true
logging:
  level: INFO
